[package]
name = "zcash-walletd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = [ "json" ] }
serde = { version = "1.0.130", features = [ "derive" ] }
serde_json = "1.0.69"
rusqlite = "0.26.1"
anyhow = "1.0.45"
dotenv = "0.15.0"
