[global]
db_path = "/data/yec-wallet-main.db"
confirmations = 6
lwd_url = "https://lite.ycash.xyz:9067"
notify_tx_url = "http://btcp:9000/zcashlikedaemoncallback/tx?cryptoCode=yec&hash="
poll_interval = 60

[debug]
address = "127.0.0.1"

[release]
address = "0.0.0.0"

