[global]
db_path = "/tmp/arrr-wallet-test.db"
confirmations = 6
lwd_url = "https://pirate.hanh.fun:9067"
#notify_tx_url = "http://btcpayserver:9000/zcashlikedaemoncallback/tx?cryptoCode=zec&hash="
notify_tx_url = "http://localhost:14142/piratelikedaemoncallback/tx?cryptoCode=arrr&hash="
poll_interval = 10

[debug]
address = "127.0.0.1"

[release]
address = "0.0.0.0"
