[global]
db_path = "zec-wallet.db"
confirmations = 10
lwd_url = "https://lite.ycash.xyz:9067"
notify_tx_url = "https://localhost:14142/zcashlikedaemoncallback/tx?cryptoCode=yec&hash="

[debug]
address = "127.0.0.1"

[release]
address = "0.0.0.0"

