[global]
db_path = "/data/zec-wallet-test.db"
confirmations = 6
lwd_url = "https://testnet.lightwalletd.com:9067"
notify_tx_url = "http://host.docker.internal:9000/zcashlikedaemoncallback/tx?cryptoCode=zec&hash="
poll_interval = 60

[debug]
address = "127.0.0.1"

[release]
address = "0.0.0.0"

